### ISSUE TITLE
Not updated with latest mapbox and problems with class

### ISSUE THREAD

**Issue by mrgithub** [binakot/Fleet-And-Staff-Location-Visualizer#1]
I'm new to Unity and noticed how well this works.  I am trying to include it into a Mapbox slippy map so it shows moving objects as the user scrolls around.

I'm very much a noob but noticed the scene is having problems compiling as its using a very old mapbox.  Also some of the objects in the Dataprovider script is broke.  I'm very new to this so please be patient with me :)

**Comment by binakot** [comment]
Hi there. I will update the mapbox sdk asap and check the data providers. This bug is possible because I'm using data from my company server which is confidential. I should to create some switcher between test and my company's data provider w/o compilation errors. Cheers ☕️

**Comment by mrgithub** [comment]
Thanks for that.  I was trying to get this to work with 'Slippy Maps' by creating an instance of an trackable object but I am new to Unity and could not get it working.  I was trying to figure out how to place an object and then move it over time across the map.  I thought your class files maybe had a method to provide new geo positions but it confused me a little.  Any chance when you update it to the latest SDK you can also get it to use Slippy Maps too please and have a simple class to update geo positions? I would be very grateful.  Thanks :)

**Comment by binakot** [comment]
Okay, I will try to code it 🍸

**Comment by binakot** [comment]
@mrgithub check the branch [issue_1](https://github.com/binakot/Fleet-And-Staff-Location-Visualizer/tree/issue_1). Is it enought for you requirements? 😋

**Comment by mrgithub** [comment]
Thanks for the help!!!  :)  Getting a problem when trying to open the 'Realistic' scene:

> Assertion failed: Removing Assets/Mapbox/Core/Plugins/sqlite/x64/sqlite3.dll because the asset does not exist

Also, how do you have a test script/class to demonstrate how the map is called, objects added and objects moved?

**Comment by binakot** [comment]
@mrgithub Is it enough? Can I merge it to master branch?

**Comment by mrgithub** [comment]
It's not working with the slippy map (can't move around map with the keyboard) and when I use low polygon maps the assets disappear under the map :/

**Comment by binakot** [comment]
@mrgithub Use WASD for camera movement and hold RMB to rotate. https://github.com/binakot/Fleet-And-Staff-Location-Visualizer/blob/master/FleetAndStaffLocationVisualizer/Assets/Scripts/Helpers/FreeFlightCamera.cs

**Comment by binakot** [comment]
@mrgithub Scene with name **Realistic** is a slippy map, but it's with zoom 16. In mapbox's examples they just use zoom 11. About objects under map. After 1.0 release, MapBox changed a lot of things and my height corrector was broken. https://github.com/binakot/Fleet-And-Staff-Location-Visualizer/blob/master/FleetAndStaffLocationVisualizer/Assets/Scripts/Helpers/HeightCorrector.cs. I will fix it asap.

**Comment by binakot** [comment]
@mrgithub Okay, I fixed the height correcting. Now You can fly with WASD & RMB. And all objects are right on the ground 🍰 Also I added one more scene with the slippy map right from the examples and few objects on it.

**Comment by mrgithub** [comment]
Looking good.  I've just played around with it and seems much better :)  I will experiment some more and see how it goes :)

**Comment by binakot** [comment]
@mrgithub When u finish ur experiments, write here, please. I'll merge this one into master branch.

**Comment by binakot** [comment]
**issue_1** branch merged into **master**.
MapBox SDK updated to last version.
Fixed compile errors.
Added few enhancements.
☕️
